name: cerb-docs

services:
  jekyll:
    build:
      context: .
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - .:/var/cerb-docs
    environment:
      JEKYLL_ENV: development
  jekyll-build:
    build:
      context: .
    volumes:
      - .:/var/cerb-docs
    environment:
      JEKYLL_ENV: production
    command: bundle exec jekyll build
    profiles: [build]